<a href="https://colab.research.google.com/github/Oliwer1992/kurs/blob/main/01_wprowadzenie/01_numpy_podstawy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### 1D Array

In [19]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


### Typ obiektu

In [9]:
type(x)

numpy.ndarray

### Wymiar tablicy

In [12]:
x.ndim

1

### Kształt tablicy

In [13]:
x.shape

(3,)

### Liczba elementów w tablicy

In [14]:
x.size

3

### Typ danych

In [15]:
x.dtype

dtype('int64')

### 2D Array

In [27]:
y = np.array([[1, 2, 3],
             [4, 5, 6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [22]:
y.ndim

2

In [23]:
y.shape

(2, 3)

In [24]:
y.size

6

In [26]:
y.dtype

dtype('int64')

### 3D Array

In [31]:
x = np.array(
    [[[1, 2, 3],
      [4, 5, 6]],

     [[4, 1, 2],
      [4, 2, 1]]]
)
print(x)

[[[1 2 3]
  [4 5 6]]

 [[4 1 2]
  [4 2 1]]]


In [32]:
x.ndim

3

In [33]:
x.shape

(2, 2, 3)

### Typy danych

In [34]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [35]:
B = np.array([1.0, 2.1, 2.2])
B.dtype

dtype('float64')

### Tworzenie tablicy z konkretnym typem danych

In [37]:
A = np.array([1, 2, 3], dtype='float')
print(A)
A.dtype

[1. 2. 3.]


dtype('float64')

### Zmiana float na int ucina do wartości całkowitej

In [41]:
B = np.array([2.2, 3.7, 8.9], dtype='int')
B.dtype
print(B)

[2 3 8]


In [42]:
C = np.array([True, False])
C.dtype

dtype('bool')

### Wbudowane typy danych

In [44]:
A = np.array([1, 2, 30], dtype=np.uint8)
A.dtype

dtype('uint8')

### Wbudowane tablice

In [47]:
np.zeros(shape=(4, 10), dtype='int') # Tablica samych zer shape(wiersze, kolumny), typ danych domyślnie float

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
np.ones(shape=(5, 5)) # Tablica samych jedynek

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.full(shape=(3, 3), fill_value=4, dtype='int') # Tablica z konkretną wartością

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [50]:
np.arange(11) # Tworzy tablice od 0-10 dziala jak range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [52]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [54]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [55]:
np.linspace(start=0, stop=1, num=11) # Zwraca 11 liczb z przedziału od 0 do 1(równo rozłożone)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [57]:
A = np.arange(15)


In [59]:
A.reshape((3, 5)) # Zmiana kształtu tablicy (wiersze, kolumny)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
A.reshape(3, -1) # Zakładamy że chcemy 3 wierwsze a -1 powoduje że liczba kolumn jest dobierana automatycznie

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
A.reshape(-1, 3) # Zakładamy że chcemy 3 kolumny a -1 powoduje że liczba wierszy jest dobierana automatycznie

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Podstawowe operacje na tablicach

In [62]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])
print(A)
print(B)

[1 2 3 4]
[5 6 7 8]


In [63]:
A + B # Dodawanie

array([ 6,  8, 10, 12])

In [73]:
np.add(A, B) # Dodawanie

array([ 6,  8, 10, 12])

In [64]:
A - B # Odejmowanie

array([-4, -4, -4, -4])

In [74]:
np.subtract(A, B) # Odejmowanie

array([-4, -4, -4, -4])

In [71]:
A * B # mnożenie po elementach

array([ 5, 12, 21, 32])

In [75]:
np.multiply(A, B) # mnożenie po elementach

array([ 5, 12, 21, 32])

In [66]:
A / B # Dzielenie, typ wyniku jest zwracany jako float

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [76]:
np.divide(A, B) # Dzielenie, typ wyniku jest zwracany jako float

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [67]:
A + 3 # Dodawanie stałej do każdego elementu

array([4, 5, 6, 7])

In [68]:
A -  2 # Odejmowanie stałej od każdego elementu



array([-1,  0,  1,  2])

In [69]:
3 * A # mnożenie stałej razy każdy element tablicy

array([ 3,  6,  9, 12])

In [70]:
A + 3*B

array([16, 20, 24, 28])

In [77]:
X = np.array([[1, 3],
              [-2, 0]])
Y = np.array([[6, 0],
              [-1, 2]])


In [78]:
X @ Y # Mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

In [79]:
np.dot(X, Y) # Mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

In [80]:
X.dot(Y) # Mnożenie macierzowe (nie jest przemienne)

array([[  3,   6],
       [-12,   0]])

### Generowanie liczb pseudolosowych  

In [81]:
np.random.seed(0) # Ziarno losowe żeby mieć taki sam wynik przy każdym losowaniu

In [82]:
np.random.randn() # Losowy rozkład normalny

1.764052345967664

In [83]:
np.random.randn(10) # 10 losowych elementów z rozkładu normalnego

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [84]:
np.random.randn(10, 4) #(wiersze, kolumny) (próbki, zmienne)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [85]:
np.random.rand() # Rozkład jednostajny na przedziale 0-1 (1 nie należy do przedziału)

0.1965823616800535

In [86]:
np.random.rand(10) # 10 elementów z przedziały 0-1

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [87]:
np.random.rand(10, 2) # (wiersze, kolumny) z przedziału 0-1

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [88]:
np.random.randint(10) # Losowa liczba całkowita z przedziału 0-10 (10 nie należy do przedziału)

3

In [89]:
np.random.randint(low=10, high=100) # Losowa liczba z przedziału 10-99

56

In [90]:
np.random.randint(low=10, high=100, size=10) # 10 losowych liczb z przedziału 10-99

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [92]:
np.random.choice([7, 2, 1, 3, 5]) # Losowy element z podanej listy

np.int64(3)

In [93]:
np.random.choice(['python', 'java', 'sql']) # Losowy element z podanej listy

np.str_('python')

In [94]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.random.shuffle(data) # Zmienia kolejność elementów w tablicy losowo
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

### Podstawowe funkcje

In [96]:
np.exp(1) # Liczba e

np.float64(7.38905609893065)

In [98]:
np.sqrt(9) # Pierwistek

np.float64(3.0)

In [101]:
np.all([2, 3, -2]) # Zwraca True jeżeli wszystkie wartości są True

np.True_

In [102]:
np.any([2, 0, -2]) # Zwraca True jeżeli którykolwiek element jest True

np.True_

In [103]:
bool(0) # False
bool(1) # True dla każdej innej liczby

True

In [104]:
A  = np.random.rand(5)
print(A)

[0.29743695 0.81379782 0.39650574 0.8811032  0.58127287]


In [105]:
np.argmax(A) # Zwraca indeks największej wartości

np.int64(3)

In [106]:
A[np.argmax(A)] # Zwraca największą wartość

np.float64(0.8811031971111616)

In [107]:
np.argmin(A)

np.int64(0)

In [108]:
A[np.argmin(A)]

np.float64(0.29743695085513366)

In [110]:
np.argsort(A) # Zwraca tablice posortowanych indeksów od min do max

array([0, 2, 4, 1, 3])

In [111]:
np.max(A) # Zwraca max

np.float64(0.8811031971111616)

In [113]:
np.min(A) # Zwraca min

np.float64(0.29743695085513366)

In [112]:
np.mean(A) # Zwraca średnią

np.float64(0.5940233162303231)

In [114]:
np.median(A) # Zwraca medianę

np.float64(0.5812728726358587)

In [115]:
np.std(A) # Zwraca odchylenie standardowe

np.float64(0.2270924608641256)

### Indeksowanie, wycinanie

In [117]:
A = np.arange(20)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [118]:
A[1] # indeks 1

np.int64(1)

In [119]:
A[1:5] # Zakres 1-4

array([1, 2, 3, 4])

In [120]:
A[:5] # Od 0 do 4

array([0, 1, 2, 3, 4])

In [121]:
A[4:] # od 4 do końca

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [122]:
A[-1] # Ostatni element

np.int64(19)

In [124]:
A = A.reshape(4, 5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [125]:
A[0] # Cały pierwszy wiersz

array([0, 1, 2, 3, 4])

In [126]:
A[:,0] # Pierwsza kolumna

array([ 0,  5, 10, 15])

In [127]:
A[:,-1] # Ostatnia kolumna

array([ 4,  9, 14, 19])

In [128]:
A[1, 1] # Konkretny element [indeks wiersza, indeks kolumny]

np.int64(6)

In [131]:
A[1:3, 1:4] # Zwraca konkretny zakres wiersze od 1-2, kolumny od 1-3

array([[ 6,  7,  8],
       [11, 12, 13]])

In [133]:
A[1, 2] = 14 # Przypisywanie nowych wartości do tablicy
print(A)

[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Iteracje po tablicach

In [134]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [135]:
for row in A:
  print(row[0])

0
5
10
15


In [137]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [139]:
for item in A.flat: # Flat spłaszcza tablice do 1D i iterujemy po każdym elemencie
  print(item)


0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### Zmiana rozmiaru tablic

In [140]:
A.shape

(4, 5)

In [141]:
A.reshape(5, 4) # Zmiana rozmiaru tablicy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [143]:
A.ravel() # Spłaszcza tablice do 1D

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [144]:
A.T # Transponowanie

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### Maski logiczne

In [145]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
print(A)

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]


In [146]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [147]:
A[A > 0] # Wycina tylko dodatnie elementy

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [149]:
np.bitwise_and(A > -5, A < 5) # Zwraca True jeżeli elementy spełniają oba warunki

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [150]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [151]:
A[np.bitwise_or(A < -5, A > 5)] # Zwraca elementy spełniające jeden z warunków

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])